#ifndef __GPIO_INIT_H
#define __GPIO_INIT_H

// #define JY61P_SCL_INDEX FFREERTOS_GPIO_PIN_INDEX(4,0,14)
// #define JY61P_SDA_INDEX FFREERTOS_GPIO_PIN_INDEX(4,0,15)

#define JY61P_SCL_INDEX FFREERTOS_GPIO_PIN_INDEX(3,0,2)
#define JY61P_SDA_INDEX FFREERTOS_GPIO_PIN_INDEX(3,0,1)

void Jy61pSclInitOut(void);
void Jy61pSdaInitOut(void);

#endif