# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jimkwokying/projectTest/masterdevice/PySide6-GUI/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 725)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.Main_QW = QtWidgets.QWidget(MainWindow)
        self.Main_QW.setObjectName("Main_QW")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Main_QW)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_QF = QtWidgets.QFrame(self.Main_QW)
        self.Main_QF.setStyleSheet("QFrame#Main_QF{\n"
"    background-color: rgb(85, 87, 83);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.Main_QF.setObjectName("Main_QF")
        self.main_qframe = QtWidgets.QHBoxLayout(self.Main_QF)
        self.main_qframe.setContentsMargins(0, 0, 0, 0)
        self.main_qframe.setSpacing(0)
        self.main_qframe.setObjectName("main_qframe")
        self.LeftMenuBg = QtWidgets.QFrame(self.Main_QF)
        self.LeftMenuBg.setMinimumSize(QtCore.QSize(68, 0))
        self.LeftMenuBg.setMaximumSize(QtCore.QSize(68, 16777215))
        self.LeftMenuBg.setStyleSheet("QFrame#LeftMenuBg{\n"
"    background-color:rgb(85, 87, 83);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.LeftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuBg.setObjectName("LeftMenuBg")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LeftMenuBg)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TopLogoInfo = QtWidgets.QFrame(self.LeftMenuBg)
        self.TopLogoInfo.setEnabled(True)
        self.TopLogoInfo.setMinimumSize(QtCore.QSize(0, 70))
        self.TopLogoInfo.setMaximumSize(QtCore.QSize(16777215, 70))
        self.TopLogoInfo.setStyleSheet("")
        self.TopLogoInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopLogoInfo.setObjectName("TopLogoInfo")
        self.Author = QtWidgets.QLabel(self.TopLogoInfo)
        self.Author.setGeometry(QtCore.QRect(90, 30, 60, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Author.sizePolicy().hasHeightForWidth())
        self.Author.setSizePolicy(sizePolicy)
        self.Author.setMinimumSize(QtCore.QSize(60, 30))
        self.Author.setMaximumSize(QtCore.QSize(60, 30))
        self.Author.setStyleSheet("font: italic 11pt \"Segoe UI\";\n"
"color: rgba(255, 255, 255, 255);")
        self.Author.setText("")
        self.Author.setAlignment(QtCore.Qt.AlignCenter)
        self.Author.setObjectName("Author")
        self.Title = QtWidgets.QLabel(self.TopLogoInfo)
        self.Title.setGeometry(QtCore.QRect(60, 10, 121, 20))
        self.Title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Title.setStyleSheet("font: 600 13pt \"Segoe UI Semibold\";\n"
"color: rgba(255, 255, 255, 255);")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.widget = QtWidgets.QWidget(self.TopLogoInfo)
        self.widget.setGeometry(QtCore.QRect(10, 20, 50, 50))
        self.widget.setMaximumSize(QtCore.QSize(50, 50))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("image:url(:/all/img/logo1.png);")
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.TopLogoInfo)
        self.ToggleBox = QtWidgets.QFrame(self.LeftMenuBg)
        self.ToggleBox.setMinimumSize(QtCore.QSize(200, 80))
        self.ToggleBox.setMaximumSize(QtCore.QSize(200, 80))
        self.ToggleBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ToggleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ToggleBox.setObjectName("ToggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ToggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ToggleBotton = QtWidgets.QPushButton(self.ToggleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton.sizePolicy().hasHeightForWidth())
        self.ToggleBotton.setSizePolicy(sizePolicy)
        self.ToggleBotton.setMinimumSize(QtCore.QSize(0, 45))
        self.ToggleBotton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ToggleBotton.setFont(font)
        self.ToggleBotton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ToggleBotton.setMouseTracking(True)
        self.ToggleBotton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton.setAutoFillBackground(False)
        self.ToggleBotton.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/menu.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 23px solid transparent;\n"
"\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton.setIcon(icon)
        self.ToggleBotton.setAutoDefault(False)
        self.ToggleBotton.setDefault(False)
        self.ToggleBotton.setFlat(False)
        self.ToggleBotton.setObjectName("ToggleBotton")
        self.verticalLayout_4.addWidget(self.ToggleBotton)
        self.verticalLayout_2.addWidget(self.ToggleBox)
        self.MenuBox = QtWidgets.QFrame(self.LeftMenuBg)
        self.MenuBox.setMinimumSize(QtCore.QSize(200, 0))
        self.MenuBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.MenuBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MenuBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuBox.setObjectName("MenuBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.MenuBox)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(15)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.src_file_button = QtWidgets.QPushButton(self.MenuBox)
        self.src_file_button.setMinimumSize(QtCore.QSize(0, 45))
        self.src_file_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.src_file_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/file.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 23px solid transparent;\n"
"\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.src_file_button.setObjectName("src_file_button")
        self.verticalLayout_5.addWidget(self.src_file_button)
        self.src_cam_button = QtWidgets.QPushButton(self.MenuBox)
        self.src_cam_button.setMinimumSize(QtCore.QSize(0, 45))
        self.src_cam_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.src_cam_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/cam.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 23px solid transparent;\n"
"\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.src_cam_button.setObjectName("src_cam_button")
        self.verticalLayout_5.addWidget(self.src_cam_button)
        self.src_rtsp_button = QtWidgets.QPushButton(self.MenuBox)
        self.src_rtsp_button.setMinimumSize(QtCore.QSize(0, 45))
        self.src_rtsp_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.src_rtsp_button.setAutoFillBackground(False)
        self.src_rtsp_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/RTSP.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 23px solid transparent;\n"
"\n"
"text-align: center;\n"
"padding-left: 0px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 12pt \"Nirmala UI\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(114, 129, 214, 59);\n"
"}")
        self.src_rtsp_button.setObjectName("src_rtsp_button")
        self.verticalLayout_5.addWidget(self.src_rtsp_button)
        self.label_2 = QtWidgets.QLabel(self.MenuBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.log_list = QtWidgets.QListWidget(self.MenuBox)
        self.log_list.setEnabled(True)
        self.log_list.setStyleSheet("QListWidget{\n"
"background-color: rgba(12, 28, 77, 0);\n"
"\n"
"border-radius:0px;\n"
"font-family: \"Microsoft YaHei\";\n"
"font-size: 16px;\n"
"color: rgb(218, 218, 218);\n"
"}")
        self.log_list.setObjectName("log_list")
        item = QtWidgets.QListWidgetItem()
        self.log_list.addItem(item)
        self.verticalLayout_5.addWidget(self.log_list)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_2.addWidget(self.MenuBox)
        self.VersionInfo = QtWidgets.QFrame(self.LeftMenuBg)
        self.VersionInfo.setMinimumSize(QtCore.QSize(200, 10))
        self.VersionInfo.setMaximumSize(QtCore.QSize(200, 15))
        self.VersionInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VersionInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VersionInfo.setObjectName("VersionInfo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.VersionInfo)
        self.verticalLayout_3.setContentsMargins(18, 0, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VersionLabel = QtWidgets.QLabel(self.VersionInfo)
        self.VersionLabel.setStyleSheet("font: 900 italic 10pt \"Segoe UI\";\n"
"color: rgba(255, 255, 255, 199);")
        self.VersionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VersionLabel.setObjectName("VersionLabel")
        self.verticalLayout_3.addWidget(self.VersionLabel)
        self.verticalLayout_2.addWidget(self.VersionInfo)
        self.ToggleBox.raise_()
        self.MenuBox.raise_()
        self.VersionInfo.raise_()
        self.TopLogoInfo.raise_()
        self.main_qframe.addWidget(self.LeftMenuBg)
        self.ContentBox = QtWidgets.QFrame(self.Main_QF)
        self.ContentBox.setStyleSheet("QFrame#ContentBox{\n"
"    background-color: rgb(245, 249, 254);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.ContentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ContentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ContentBox.setObjectName("ContentBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ContentBox)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.top = QtWidgets.QFrame(self.ContentBox)
        self.top.setMinimumSize(QtCore.QSize(0, 30))
        self.top.setMaximumSize(QtCore.QSize(16777215, 30))
        self.top.setStyleSheet("QFrame#top{\n"
"background-color: rgb(85, 87, 83);\n"
"}")
        self.top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout.setContentsMargins(20, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.explain_title = QtWidgets.QLabel(self.top)
        self.explain_title.setMinimumSize(QtCore.QSize(0, 30))
        self.explain_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.explain_title.setStyleSheet("font: 700 italic 11pt \"Segoe UI\";")
        self.explain_title.setAlignment(QtCore.Qt.AlignCenter)
        self.explain_title.setObjectName("explain_title")
        self.horizontalLayout.addWidget(self.explain_title)
        self.buttons_sf = QtWidgets.QFrame(self.top)
        self.buttons_sf.setMinimumSize(QtCore.QSize(120, 30))
        self.buttons_sf.setMaximumSize(QtCore.QSize(120, 30))
        self.buttons_sf.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_sf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_sf.setObjectName("buttons_sf")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttons_sf)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settings_button = QtWidgets.QPushButton(self.buttons_sf)
        self.settings_button.setMinimumSize(QtCore.QSize(0, 20))
        self.settings_button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.settings_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/set.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.settings_button.setText("")
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout_2.addWidget(self.settings_button)
        self.min_sf = QtWidgets.QPushButton(self.buttons_sf)
        self.min_sf.setMinimumSize(QtCore.QSize(14, 14))
        self.min_sf.setMaximumSize(QtCore.QSize(14, 14))
        self.min_sf.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(4, 180, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.min_sf.setText("")
        self.min_sf.setObjectName("min_sf")
        self.horizontalLayout_2.addWidget(self.min_sf)
        self.max_sf = QtWidgets.QPushButton(self.buttons_sf)
        self.max_sf.setMinimumSize(QtCore.QSize(14, 14))
        self.max_sf.setMaximumSize(QtCore.QSize(14, 14))
        self.max_sf.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(227, 199, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.max_sf.setText("")
        self.max_sf.setObjectName("max_sf")
        self.horizontalLayout_2.addWidget(self.max_sf)
        self.close_button = QtWidgets.QPushButton(self.buttons_sf)
        self.close_button.setMinimumSize(QtCore.QSize(14, 14))
        self.close_button.setMaximumSize(QtCore.QSize(14, 14))
        self.close_button.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(240, 108, 96);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.horizontalLayout.addWidget(self.buttons_sf)
        self.verticalLayout_6.addWidget(self.top)
        self.content = QtWidgets.QFrame(self.ContentBox)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.main_content = QtWidgets.QVBoxLayout()
        self.main_content.setSpacing(5)
        self.main_content.setObjectName("main_content")
        self.char_label = QtWidgets.QLabel(self.content)
        self.char_label.setMinimumSize(QtCore.QSize(0, 20))
        self.char_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.char_label.setFont(font)
        self.char_label.setStyleSheet("padding-left:12px;")
        self.char_label.setObjectName("char_label")
        self.main_content.addWidget(self.char_label)
        self.QF_Group = QtWidgets.QFrame(self.content)
        self.QF_Group.setMinimumSize(QtCore.QSize(0, 100))
        self.QF_Group.setMaximumSize(QtCore.QSize(16777215, 100))
        self.QF_Group.setStyleSheet("QFrame#QF_Group{\n"
"background-color: rgb(238, 242, 255);\n"
"border:2px solid rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"}")
        self.QF_Group.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QF_Group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QF_Group.setObjectName("QF_Group")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.QF_Group)
        self.horizontalLayout_3.setContentsMargins(-1, 9, -1, 15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Class_QF = QtWidgets.QFrame(self.QF_Group)
        self.Class_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Class_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Class_QF.setToolTipDuration(0)
        self.Class_QF.setStyleSheet("QFrame#Class_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color:rgb(136, 138, 133);\n"
"border: 1px outset rgb(98, 91, 213);\n"
"}\n"
"")
        self.Class_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Class_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Class_QF.setObjectName("Class_QF")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Class_QF)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Class_top = QtWidgets.QFrame(self.Class_QF)
        self.Class_top.setStyleSheet("border:none")
        self.Class_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Class_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Class_top.setObjectName("Class_top")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Class_top)
        self.horizontalLayout_6.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.Class_top)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"padding-left:12px;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.verticalLayout_7.addWidget(self.Class_top)
        self.line_2 = QtWidgets.QFrame(self.Class_QF)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.Class_bottom = QtWidgets.QFrame(self.Class_QF)
        self.Class_bottom.setStyleSheet("border:none")
        self.Class_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Class_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Class_bottom.setObjectName("Class_bottom")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Class_bottom)
        self.verticalLayout_8.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Class_num = QtWidgets.QLabel(self.Class_bottom)
        self.Class_num.setMinimumSize(QtCore.QSize(0, 30))
        self.Class_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Class_num.setFont(font)
        self.Class_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 17pt \"Microsoft YaHei UI\";")
        self.Class_num.setText("")
        self.Class_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Class_num.setObjectName("Class_num")
        self.verticalLayout_8.addWidget(self.Class_num, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.Class_bottom)
        self.verticalLayout_7.setStretch(1, 2)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_3.addWidget(self.Class_QF)
        self.Target_QF = QtWidgets.QFrame(self.QF_Group)
        self.Target_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Target_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Target_QF.setToolTipDuration(0)
        self.Target_QF.setStyleSheet("QFrame#Target_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: rgb(186, 189, 182);\n"
"border: 1px outset rgb(252, 194, 149)\n"
"}\n"
"")
        self.Target_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Target_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Target_QF.setObjectName("Target_QF")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Target_QF)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Target_top = QtWidgets.QFrame(self.Target_QF)
        self.Target_top.setStyleSheet("border:none")
        self.Target_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Target_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Target_top.setObjectName("Target_top")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Target_top)
        self.horizontalLayout_7.setContentsMargins(0, 3, 0, 3)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.Target_top)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"padding-left:12px;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.verticalLayout_9.addWidget(self.Target_top)
        self.line_3 = QtWidgets.QFrame(self.Target_QF)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_9.addWidget(self.line_3)
        self.Target_bottom = QtWidgets.QFrame(self.Target_QF)
        self.Target_bottom.setStyleSheet("border:none")
        self.Target_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Target_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Target_bottom.setObjectName("Target_bottom")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Target_bottom)
        self.verticalLayout_10.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Target_num = QtWidgets.QLabel(self.Target_bottom)
        self.Target_num.setMinimumSize(QtCore.QSize(0, 30))
        self.Target_num.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Target_num.setFont(font)
        self.Target_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 17pt \"Microsoft YaHei UI\";")
        self.Target_num.setText("")
        self.Target_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Target_num.setObjectName("Target_num")
        self.verticalLayout_10.addWidget(self.Target_num, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_9.addWidget(self.Target_bottom)
        self.verticalLayout_9.setStretch(1, 2)
        self.verticalLayout_9.setStretch(2, 1)
        self.horizontalLayout_3.addWidget(self.Target_QF)
        self.Fps_QF = QtWidgets.QFrame(self.QF_Group)
        self.Fps_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Fps_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Fps_QF.setToolTipDuration(0)
        self.Fps_QF.setStyleSheet("QFrame#Fps_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: rgb(211, 215, 207);\n"
"border: 1px outset rgb(153, 117, 219)\n"
"}\n"
"")
        self.Fps_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fps_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fps_QF.setObjectName("Fps_QF")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Fps_QF)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Fps_top = QtWidgets.QFrame(self.Fps_QF)
        self.Fps_top.setStyleSheet("border:none")
        self.Fps_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fps_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fps_top.setObjectName("Fps_top")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Fps_top)
        self.horizontalLayout_8.setContentsMargins(0, 3, 7, 3)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.Fps_top)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"padding-left:12px;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_7.setMidLineWidth(-1)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.verticalLayout_11.addWidget(self.Fps_top)
        self.line_4 = QtWidgets.QFrame(self.Fps_QF)
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_11.addWidget(self.line_4)
        self.Fps_bottom = QtWidgets.QFrame(self.Fps_QF)
        self.Fps_bottom.setStyleSheet("border:none")
        self.Fps_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Fps_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Fps_bottom.setObjectName("Fps_bottom")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Fps_bottom)
        self.verticalLayout_12.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fps_label = QtWidgets.QLabel(self.Fps_bottom)
        self.fps_label.setMinimumSize(QtCore.QSize(0, 30))
        self.fps_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.fps_label.setFont(font)
        self.fps_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 17pt \"Microsoft YaHei UI\";")
        self.fps_label.setText("")
        self.fps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fps_label.setObjectName("fps_label")
        self.verticalLayout_12.addWidget(self.fps_label, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_11.addWidget(self.Fps_bottom)
        self.verticalLayout_11.setStretch(1, 2)
        self.verticalLayout_11.setStretch(2, 1)
        self.horizontalLayout_3.addWidget(self.Fps_QF)
        self.Model_QF = QtWidgets.QFrame(self.QF_Group)
        self.Model_QF.setMinimumSize(QtCore.QSize(170, 80))
        self.Model_QF.setMaximumSize(QtCore.QSize(170, 80))
        self.Model_QF.setToolTipDuration(0)
        self.Model_QF.setStyleSheet("QFrame#Model_QF{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"background-color: rgb(136, 138, 133);\n"
"border: 1px outset rgb(72, 158, 204)\n"
"}\n"
"")
        self.Model_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Model_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Model_QF.setObjectName("Model_QF")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Model_QF)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Model_top = QtWidgets.QFrame(self.Model_QF)
        self.Model_top.setStyleSheet("border:none")
        self.Model_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Model_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Model_top.setObjectName("Model_top")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Model_top)
        self.horizontalLayout_9.setContentsMargins(0, 3, 7, 3)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.Model_top)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(87)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgba(255, 255, 255,210);\n"
"padding-left:12px;\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label_8.setMidLineWidth(-1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setIndent(0)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.verticalLayout_13.addWidget(self.Model_top)
        self.line_5 = QtWidgets.QFrame(self.Model_QF)
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_5.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_13.addWidget(self.line_5)
        self.Model_bottom = QtWidgets.QFrame(self.Model_QF)
        self.Model_bottom.setStyleSheet("border:none")
        self.Model_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Model_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Model_bottom.setObjectName("Model_bottom")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.Model_bottom)
        self.verticalLayout_14.setContentsMargins(0, 6, 0, 6)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.stair_label = QtWidgets.QLabel(self.Model_bottom)
        self.stair_label.setMinimumSize(QtCore.QSize(0, 30))
        self.stair_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.stair_label.setFont(font)
        self.stair_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Microsoft YaHei UI\";\n"
"")
        self.stair_label.setText("")
        self.stair_label.setAlignment(QtCore.Qt.AlignCenter)
        self.stair_label.setObjectName("stair_label")
        self.verticalLayout_14.addWidget(self.stair_label, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_13.addWidget(self.Model_bottom)
        self.verticalLayout_13.setStretch(1, 2)
        self.verticalLayout_13.setStretch(2, 1)
        self.horizontalLayout_3.addWidget(self.Model_QF)
        self.main_content.addWidget(self.QF_Group)
        self.Result_QF = QtWidgets.QFrame(self.content)
        self.Result_QF.setStyleSheet("")
        self.Result_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Result_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Result_QF.setObjectName("Result_QF")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Result_QF)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.splitter = QtWidgets.QSplitter(self.Result_QF)
        self.splitter.setStyleSheet("#splitter::handle{background: 1px solid  rgba(200, 200, 200,100);}")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.pre_video = QtWidgets.QLabel(self.splitter)
        self.pre_video.setMinimumSize(QtCore.QSize(200, 100))
        self.pre_video.setStyleSheet("background-color: rgb(238, 242, 255);\n"
"border:2px solid rgb(255, 255, 255);\n"
"border-radius:15px")
        self.pre_video.setText("")
        self.pre_video.setAlignment(QtCore.Qt.AlignCenter)
        self.pre_video.setObjectName("pre_video")
        self.res_video = QtWidgets.QLabel(self.splitter)
        self.res_video.setMinimumSize(QtCore.QSize(200, 100))
        self.res_video.setStyleSheet("background-color: rgb(238, 242, 255);\n"
"border:2px solid rgb(255, 255, 255);\n"
"border-radius:15px")
        self.res_video.setText("")
        self.res_video.setAlignment(QtCore.Qt.AlignCenter)
        self.res_video.setObjectName("res_video")
        self.verticalLayout_16.addWidget(self.splitter)
        self.main_content.addWidget(self.Result_QF)
        self.Pause_QF = QtWidgets.QFrame(self.content)
        self.Pause_QF.setMinimumSize(QtCore.QSize(0, 30))
        self.Pause_QF.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Pause_QF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pause_QF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pause_QF.setObjectName("Pause_QF")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Pause_QF)
        self.horizontalLayout_4.setContentsMargins(0, 0, 3, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.run_button = QtWidgets.QPushButton(self.Pause_QF)
        self.run_button.setMinimumSize(QtCore.QSize(0, 30))
        self.run_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.run_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_button.setMouseTracking(True)
        self.run_button.setStyleSheet("QPushButton{\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"border: none;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.run_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/all/img/begin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/all/img/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.run_button.setIcon(icon)
        self.run_button.setIconSize(QtCore.QSize(30, 30))
        self.run_button.setCheckable(True)
        self.run_button.setChecked(False)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_4.addWidget(self.run_button)
        self.progress_bar = QtWidgets.QProgressBar(self.Pause_QF)
        self.progress_bar.setMinimumSize(QtCore.QSize(0, 20))
        self.progress_bar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.progress_bar.setStyleSheet("QProgressBar{ \n"
"font: 700 10pt \"Microsoft YaHei UI\";\n"
"color: rgb(253, 143, 134); \n"
"text-align:center; \n"
"border:3px solid rgb(255, 255, 255);\n"
"border-radius: 10px; \n"
"background-color: rgba(215, 215, 215,100);\n"
"} \n"
"\n"
"QProgressBar:chunk{ \n"
"border-radius:0px; \n"
"background: rgba(119, 111, 252, 200);\n"
"border-radius: 7px;\n"
"}")
        self.progress_bar.setMaximum(1000)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout_4.addWidget(self.progress_bar)
        self.stop_button = QtWidgets.QPushButton(self.Pause_QF)
        self.stop_button.setMinimumSize(QtCore.QSize(0, 30))
        self.stop_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/stop.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"}")
        self.stop_button.setText("")
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_4.addWidget(self.stop_button)
        self.main_content.addWidget(self.Pause_QF)
        self.horizontalLayout_5.addLayout(self.main_content)
        self.prm_page = QtWidgets.QFrame(self.content)
        self.prm_page.setMinimumSize(QtCore.QSize(0, 0))
        self.prm_page.setMaximumSize(QtCore.QSize(0, 16777215))
        self.prm_page.setStyleSheet("QFrame#prm_page{\n"
"background-color: rgb(85, 87, 83);\n"
"border-top-left-radius:30px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:30px;\n"
"}")
        self.prm_page.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prm_page.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prm_page.setObjectName("prm_page")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.prm_page)
        self.verticalLayout_22.setContentsMargins(15, 15, -1, -1)
        self.verticalLayout_22.setSpacing(15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label = QtWidgets.QLabel(self.prm_page)
        self.label.setStyleSheet("padding-left: 0px;\n"
"padding-bottom: 2px;\n"
"color: rgba(255, 255, 255, 240);\n"
"font: 700 italic 16pt \"Segoe UI\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_22.addWidget(self.label)
        self.Model_QF_2 = QtWidgets.QWidget(self.prm_page)
        self.Model_QF_2.setMinimumSize(QtCore.QSize(190, 90))
        self.Model_QF_2.setMaximumSize(QtCore.QSize(190, 90))
        self.Model_QF_2.setStyleSheet("QWidget#Model_QF_2{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Model_QF_2.setObjectName("Model_QF_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.Model_QF_2)
        self.verticalLayout_21.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.ToggleBotton_6 = QtWidgets.QPushButton(self.Model_QF_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_6.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_6.setSizePolicy(sizePolicy)
        self.ToggleBotton_6.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ToggleBotton_6.setFont(font)
        self.ToggleBotton_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_6.setMouseTracking(True)
        self.ToggleBotton_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_6.setAutoFillBackground(False)
        self.ToggleBotton_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/model.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 2px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_6.setIcon(icon)
        self.ToggleBotton_6.setAutoDefault(False)
        self.ToggleBotton_6.setDefault(False)
        self.ToggleBotton_6.setFlat(False)
        self.ToggleBotton_6.setObjectName("ToggleBotton_6")
        self.verticalLayout_21.addWidget(self.ToggleBotton_6)
        self.model_box = QtWidgets.QComboBox(self.Model_QF_2)
        self.model_box.setMinimumSize(QtCore.QSize(170, 20))
        self.model_box.setMaximumSize(QtCore.QSize(170, 20))
        self.model_box.setStyleSheet("\n"
"QComboBox {\n"
"            background-color: rgba(255,255,255,90);\n"
"            color: rgba(0, 0, 0, 200);\n"
"            font: 600 9pt \"Segoe UI\";\n"
"            border: 1px solid lightgray;\n"
"            border-radius: 10px;\n"
"            padding-left: 15px;\n"
"        }\n"
"        \n"
"        QComboBox:on {\n"
"            border: 1px solid #63acfb;\n"
"        }\n"
"\n"
"        QComboBox::drop-down {\n"
"            width: 22px;\n"
"            border-left: 1px solid lightgray;\n"
"            border-top-right-radius: 15px;\n"
"            border-bottom-right-radius: 15px;\n"
"        }\n"
"        \n"
"        QComboBox::drop-down:on {\n"
"            border-left: 1px solid #63acfb;\n"
"        }\n"
"\n"
"        QComboBox::down-arrow {\n"
"            width: 16px;\n"
"            height: 16px;\n"
"            image: url(:/all/img/box_down.png);\n"
"        }\n"
"\n"
"        QComboBox::down-arrow:on {\n"
"            image: url(:/all/img/box_up.png);\n"
"        }\n"
"\n"
"        QComboBox QAbstractItemView {\n"
"            border: none;\n"
"            outline: none;\n"
"            padding: 10px;\n"
"            background-color: rgb(223, 188, 220);\n"
"        }\n"
"\n"
"\n"
"        QComboBox QScrollBar:vertical {\n"
"            width: 2px;\n"
"           background-color: rgba(255,255,255,150);\n"
"        }\n"
"\n"
"        QComboBox QScrollBar::handle:vertical {\n"
"            background-color: rgba(255,255,255,90);\n"
"        }")
        self.model_box.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.model_box.setMinimumContentsLength(0)
        self.model_box.setProperty("placeholderText", "")
        self.model_box.setObjectName("model_box")
        self.verticalLayout_21.addWidget(self.model_box)
        self.verticalLayout_22.addWidget(self.Model_QF_2)
        self.IOU_QF = QtWidgets.QFrame(self.prm_page)
        self.IOU_QF.setMinimumSize(QtCore.QSize(190, 90))
        self.IOU_QF.setMaximumSize(QtCore.QSize(190, 90))
        self.IOU_QF.setStyleSheet("QFrame#IOU_QF{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.IOU_QF.setObjectName("IOU_QF")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.IOU_QF)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.ToggleBotton_2 = QtWidgets.QPushButton(self.IOU_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_2.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_2.setSizePolicy(sizePolicy)
        self.ToggleBotton_2.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ToggleBotton_2.setFont(font)
        self.ToggleBotton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_2.setMouseTracking(True)
        self.ToggleBotton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_2.setAutoFillBackground(False)
        self.ToggleBotton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/IOU.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 4px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_2.setIcon(icon)
        self.ToggleBotton_2.setAutoDefault(False)
        self.ToggleBotton_2.setDefault(False)
        self.ToggleBotton_2.setFlat(False)
        self.ToggleBotton_2.setObjectName("ToggleBotton_2")
        self.verticalLayout_15.addWidget(self.ToggleBotton_2)
        self.frame_3 = QtWidgets.QFrame(self.IOU_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_10.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.iou_spinbox = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.iou_spinbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iou_spinbox.setStyleSheet("QDoubleSpinBox {\n"
"border: 0px solid lightgray;\n"
"border-radius: 2px;\n"
"background-color: rgba(255,255,255,90);\n"
"font: 600 9pt \"Segoe UI\";\n"
"}\n"
"        \n"
"QDoubleSpinBox::up-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/all/img/box_up.png);\n"
"}\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top: 1px;\n"
"}\n"
"            \n"
"QDoubleSpinBox::down-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/all/img/box_down.png);\n"
"}\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom: 1px;\n"
"}")
        self.iou_spinbox.setMinimum(0.01)
        self.iou_spinbox.setMaximum(1.0)
        self.iou_spinbox.setSingleStep(0.05)
        self.iou_spinbox.setProperty("value", 0.45)
        self.iou_spinbox.setObjectName("iou_spinbox")
        self.horizontalLayout_10.addWidget(self.iou_spinbox)
        self.iou_slider = QtWidgets.QSlider(self.frame_3)
        self.iou_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iou_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: none;\n"
"height: 10px;\n"
"background-color: rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 10px;\n"
"margin: -1px 0px -1px 0px;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #59969b, stop:1 #04e7fa);\n"
"border-radius: 5px;\n"
"}")
        self.iou_slider.setMinimum(1)
        self.iou_slider.setMaximum(100)
        self.iou_slider.setProperty("value", 45)
        self.iou_slider.setOrientation(QtCore.Qt.Horizontal)
        self.iou_slider.setObjectName("iou_slider")
        self.horizontalLayout_10.addWidget(self.iou_slider)
        self.verticalLayout_15.addWidget(self.frame_3)
        self.verticalLayout_22.addWidget(self.IOU_QF)
        self.Conf_QF = QtWidgets.QFrame(self.prm_page)
        self.Conf_QF.setMinimumSize(QtCore.QSize(190, 90))
        self.Conf_QF.setMaximumSize(QtCore.QSize(190, 90))
        self.Conf_QF.setStyleSheet("QFrame#Conf_QF{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Conf_QF.setObjectName("Conf_QF")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.Conf_QF)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.ToggleBotton_3 = QtWidgets.QPushButton(self.Conf_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_3.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_3.setSizePolicy(sizePolicy)
        self.ToggleBotton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ToggleBotton_3.setFont(font)
        self.ToggleBotton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_3.setMouseTracking(True)
        self.ToggleBotton_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_3.setAutoFillBackground(False)
        self.ToggleBotton_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/conf.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 4px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_3.setIcon(icon)
        self.ToggleBotton_3.setAutoDefault(False)
        self.ToggleBotton_3.setDefault(False)
        self.ToggleBotton_3.setFlat(False)
        self.ToggleBotton_3.setObjectName("ToggleBotton_3")
        self.verticalLayout_18.addWidget(self.ToggleBotton_3)
        self.frame = QtWidgets.QFrame(self.Conf_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 20))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame.setObjectName("frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_11.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.conf_spinbox = QtWidgets.QDoubleSpinBox(self.frame)
        self.conf_spinbox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.conf_spinbox.setStyleSheet("QDoubleSpinBox {\n"
"border: 0px solid lightgray;\n"
"border-radius: 2px;\n"
"background-color: rgba(255,255,255,90);\n"
"font: 600 9pt \"Segoe UI\";\n"
"}\n"
"        \n"
"QDoubleSpinBox::up-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/all/img/box_up.png);\n"
"}\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top: 1px;\n"
"}\n"
"            \n"
"QDoubleSpinBox::down-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/all/img/box_down.png);\n"
"}\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom: 1px;\n"
"}")
        self.conf_spinbox.setMinimum(0.01)
        self.conf_spinbox.setMaximum(1.0)
        self.conf_spinbox.setSingleStep(0.05)
        self.conf_spinbox.setProperty("value", 0.25)
        self.conf_spinbox.setObjectName("conf_spinbox")
        self.horizontalLayout_11.addWidget(self.conf_spinbox)
        self.conf_slider = QtWidgets.QSlider(self.frame)
        self.conf_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.conf_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: none;\n"
"height: 10px;\n"
"background-color: rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 10px;\n"
"margin: -1px 0px -1px 0px;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #59969b, stop:1 #04e7fa);\n"
"border-radius: 5px;\n"
"}")
        self.conf_slider.setMinimum(1)
        self.conf_slider.setMaximum(100)
        self.conf_slider.setProperty("value", 25)
        self.conf_slider.setOrientation(QtCore.Qt.Horizontal)
        self.conf_slider.setObjectName("conf_slider")
        self.horizontalLayout_11.addWidget(self.conf_slider)
        self.verticalLayout_18.addWidget(self.frame)
        self.verticalLayout_22.addWidget(self.Conf_QF)
        self.Delay_QF = QtWidgets.QFrame(self.prm_page)
        self.Delay_QF.setMinimumSize(QtCore.QSize(190, 90))
        self.Delay_QF.setMaximumSize(QtCore.QSize(190, 90))
        self.Delay_QF.setStyleSheet("QFrame#Delay_QF{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Delay_QF.setObjectName("Delay_QF")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.Delay_QF)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.ToggleBotton_4 = QtWidgets.QPushButton(self.Delay_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_4.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_4.setSizePolicy(sizePolicy)
        self.ToggleBotton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ToggleBotton_4.setFont(font)
        self.ToggleBotton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_4.setMouseTracking(True)
        self.ToggleBotton_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_4.setAutoFillBackground(False)
        self.ToggleBotton_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/delay.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 2px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_4.setIcon(icon)
        self.ToggleBotton_4.setAutoDefault(False)
        self.ToggleBotton_4.setDefault(False)
        self.ToggleBotton_4.setFlat(False)
        self.ToggleBotton_4.setObjectName("ToggleBotton_4")
        self.verticalLayout_19.addWidget(self.ToggleBotton_4)
        self.frame_2 = QtWidgets.QFrame(self.Delay_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_12.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.speed_spinbox = QtWidgets.QSpinBox(self.frame_2)
        self.speed_spinbox.setStyleSheet("QSpinBox {\n"
"border: 0px solid lightgray;\n"
"border-radius: 2px;\n"
"background-color: rgba(255,255,255,90);\n"
"font: 600 9pt \"Segoe UI\";\n"
"}\n"
"        \n"
"QSpinBox::up-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/all/img/box_up.png);\n"
"}\n"
"QSpinBox::up-button:pressed {\n"
"margin-top: 1px;\n"
"}\n"
"            \n"
"QSpinBox::down-button {\n"
"width: 10px;\n"
"height: 9px;\n"
"margin: 0px 3px 0px 0px;\n"
"border-image: url(:/all/img/box_down.png);\n"
"}\n"
"QSpinBox::down-button:pressed {\n"
"margin-bottom: 1px;\n"
"}")
        self.speed_spinbox.setMaximum(50)
        self.speed_spinbox.setProperty("value", 10)
        self.speed_spinbox.setObjectName("speed_spinbox")
        self.horizontalLayout_12.addWidget(self.speed_spinbox)
        self.speed_slider = QtWidgets.QSlider(self.frame_2)
        self.speed_slider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speed_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"border: none;\n"
"height: 10px;\n"
"background-color: rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"width: 10px;\n"
"margin: -1px 0px -1px 0px;\n"
"border-radius: 3px;\n"
"background-color: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"border-radius: 5px;\n"
"}")
        self.speed_slider.setMaximum(50)
        self.speed_slider.setProperty("value", 10)
        self.speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.speed_slider.setObjectName("speed_slider")
        self.horizontalLayout_12.addWidget(self.speed_slider)
        self.verticalLayout_19.addWidget(self.frame_2)
        self.verticalLayout_22.addWidget(self.Delay_QF)
        self.Save_QF = QtWidgets.QFrame(self.prm_page)
        self.Save_QF.setMinimumSize(QtCore.QSize(190, 120))
        self.Save_QF.setMaximumSize(QtCore.QSize(190, 120))
        self.Save_QF.setStyleSheet("QFrame#Save_QF{\n"
"border:2px solid rgba(255, 255, 255, 70);\n"
"border-radius:15px;\n"
"}")
        self.Save_QF.setObjectName("Save_QF")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.Save_QF)
        self.verticalLayout_20.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.ToggleBotton_5 = QtWidgets.QPushButton(self.Save_QF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToggleBotton_5.sizePolicy().hasHeightForWidth())
        self.ToggleBotton_5.setSizePolicy(sizePolicy)
        self.ToggleBotton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.ToggleBotton_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.ToggleBotton_5.setFont(font)
        self.ToggleBotton_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ToggleBotton_5.setMouseTracking(True)
        self.ToggleBotton_5.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ToggleBotton_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ToggleBotton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ToggleBotton_5.setAutoFillBackground(False)
        self.ToggleBotton_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/all/img/save.png);\n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"border: none;\n"
"border-left: 20px solid transparent;\n"
"\n"
"text-align: left;\n"
"padding-left: 40px;\n"
"padding-bottom: 2px;\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 700 13pt \"Nirmala UI\";\n"
"}")
        icon = QtGui.QIcon.fromTheme("zoom-out")
        self.ToggleBotton_5.setIcon(icon)
        self.ToggleBotton_5.setAutoDefault(False)
        self.ToggleBotton_5.setDefault(False)
        self.ToggleBotton_5.setFlat(False)
        self.ToggleBotton_5.setObjectName("ToggleBotton_5")
        self.verticalLayout_20.addWidget(self.ToggleBotton_5)
        self.save_res_button = QtWidgets.QCheckBox(self.Save_QF)
        self.save_res_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_res_button.setStyleSheet("QCheckBox {\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 590 10pt \"Nirmala UI\";\n"
"        }\n"
"\n"
"        QCheckBox::indicator {\n"
"            padding-top: 1px;\n"
"padding-left: 10px;\n"
"            width: 40px;\n"
"            height: 30px;\n"
"            border: none;\n"
"        }\n"
"\n"
"        QCheckBox::indicator:unchecked {\n"
"            image: url(:/all/img/check_no.png);\n"
"        }\n"
"\n"
"        QCheckBox::indicator:checked {\n"
"            image: url(:/all/img/check_yes.png);\n"
"        }")
        self.save_res_button.setObjectName("save_res_button")
        self.verticalLayout_20.addWidget(self.save_res_button)
        self.save_txt_button = QtWidgets.QCheckBox(self.Save_QF)
        self.save_txt_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_txt_button.setStyleSheet("QCheckBox {\n"
"color: rgba(255, 255, 255, 199);\n"
"font: 590 10pt \"Nirmala UI\";\n"
"        }\n"
"\n"
"        QCheckBox::indicator {\n"
"            padding-top: 1px;\n"
"padding-left: 10px;\n"
"            width: 40px;\n"
"            height: 30px;\n"
"            border: none;\n"
"        }\n"
"\n"
"        QCheckBox::indicator:unchecked {\n"
"            image: url(:/all/img/check_no.png);\n"
"        }\n"
"\n"
"        QCheckBox::indicator:checked {\n"
"            image: url(:/all/img/check_yes.png);\n"
"        }")
        self.save_txt_button.setObjectName("save_txt_button")
        self.verticalLayout_20.addWidget(self.save_txt_button)
        self.verticalLayout_22.addWidget(self.Save_QF)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.prm_page)
        self.verticalLayout_6.addWidget(self.content)
        self.below = QtWidgets.QFrame(self.ContentBox)
        self.below.setMinimumSize(QtCore.QSize(0, 30))
        self.below.setMaximumSize(QtCore.QSize(16777215, 30))
        self.below.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.below.setFrameShadow(QtWidgets.QFrame.Raised)
        self.below.setObjectName("below")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.below)
        self.horizontalLayout_13.setContentsMargins(20, 2, 0, 4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.status_bar = QtWidgets.QLabel(self.below)
        self.status_bar.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color: rgba(0, 0, 0, 140);")
        self.status_bar.setObjectName("status_bar")
        self.horizontalLayout_13.addWidget(self.status_bar)
        self.frame_size_grip = QtWidgets.QFrame(self.below)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setStyleSheet("border-radius:30px;")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_13.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.below)
        self.main_qframe.addWidget(self.ContentBox)
        self.verticalLayout.addWidget(self.Main_QF)
        MainWindow.setCentralWidget(self.Main_QW)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "SystemGUI"))
        self.ToggleBotton.setText(_translate("MainWindow", "Hide"))
        self.src_file_button.setText(_translate("MainWindow", "Local File"))
        self.src_cam_button.setText(_translate("MainWindow", "Camera"))
        self.src_rtsp_button.setText(_translate("MainWindow", "Rtsp"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#eeeeec;\">System Log</span></p></body></html>"))
        __sortingEnabled = self.log_list.isSortingEnabled()
        self.log_list.setSortingEnabled(False)
        item = self.log_list.item(0)
        item.setText(_translate("MainWindow", "system log:"))
        self.log_list.setSortingEnabled(__sortingEnabled)
        self.VersionLabel.setText(_translate("MainWindow", "Version: 1.0"))
        self.explain_title.setText(_translate("MainWindow", "Blind Helping System GUI"))
        self.char_label.setText(_translate("MainWindow", "Detection"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>GPS</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>FPS1</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Fps"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Stair Num</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.ToggleBotton_6.setText(_translate("MainWindow", "Model"))
        self.ToggleBotton_2.setText(_translate("MainWindow", "IOU"))
        self.ToggleBotton_3.setText(_translate("MainWindow", "Conf"))
        self.ToggleBotton_4.setText(_translate("MainWindow", "Delay(ms)"))
        self.ToggleBotton_5.setText(_translate("MainWindow", "Save"))
        self.save_res_button.setText(_translate("MainWindow", "Save MP4/JPG"))
        self.save_txt_button.setText(_translate("MainWindow", "Save Labels(.txt)"))
        self.status_bar.setText(_translate("MainWindow", "Welcome!"))
import resources_rc
