include $(PROJECT_DIR)/sdkconfig


BUILD_PATH := $(BUILD_OUT_PATH)/$(shell pwd)

CSRCS_RELATIVE_FILES := fassert.c \
				fdebug.c \
				felf.c \
				finterrupt.c \
				fprintf.c \
				fprintk.c \
				fsleep.c  \
				fimage_info.c
#LIBS_NAME ?= libcommon

include $(SDK_DIR)/tools/build/compiler.mk