
BUILD_INC_PATH_DIR += $(SDK_DIR)/arch/$(CONFIG_ARCH_NAME)/common
BUILD_INC_PATH_DIR += $(SDK_DIR)/arch/$(CONFIG_ARCH_NAME)/$(CONFIG_ARCH_EXECUTION_STATE) \
				 $(SDK_DIR)/arch/$(CONFIG_ARCH_NAME)/$(CONFIG_ARCH_EXECUTION_STATE)/$(CONFIG_TOOLCHAIN_NAME) 


BUILD_INC_PATH_DIR += $(SDK_DIR)/arch/$(CONFIG_ARCH_NAME)/$(CONFIG_TOOLCHAIN_NAME)
